import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 기본설정이 캐싱 안함. next.config에서 설정 가능 또는 요청보낼때 cache: "force-cache"설정 */}
        <h1>NextJS 15</h1>
        <nav>
          {/* Full Refresh, Soft Navigate 다 바뀜 */}
          <Link href="/" className="p-4">
            Home
          </Link>
          {/* Full Refresh, Soft Navigate 다 바뀜 */}
          {/* export const dynamic = "force-static"로 정적 페이지로 만들었을때 개발환경과 운영환경에서 캐싱이 다르게 동작함 */}
          <Link href="/about" className="p-4">
            About
          </Link>
          {/* 다 바뀜 */}
          <Link href="/api/time" className="p-4">
            API
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
